# Generated by Django 5.0.1 on 2024-01-14 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonial",
            old_name="Attribution",
            new_name="attribution",
        ),
    ]
